version: "3.9"
services:
    backend:
        image: forcasting-java
        container_name: forecasting
        build:
            context: ./forecasting
        ports:
            - "9200:9200"
    frontend:
        image: uefaek2024pronoapp
        container_name: forecasting-ui
        build:
            context: ./uefa-ek-2024-prono-app
        ports:
            - "8080:8080"
        depends_on:
            - backend